
from utils.Palabra import Palabra
from utils.Relacion import Relacion

from grafico14 import generate_graph

texto = ""
def test1():
    list_palabras = []
    list_relaciones= []
    list_palabras.append(Palabra('Austrias', 'PROPN', 'nsubj', 10, 1004, 0, False, 'Austrias', 4))
    list_palabras.append(Palabra('España', 'PROPN', 'obj', 11, 1024, 0, False, 'España', 24))
    list_palabras.append(Palabra('siglo', 'NOUN', 'obl', 12, 1037, 0, False, 'siglo', 37))
    list_palabras.append(Palabra('XVI', 'NOUN', 'compound', 13, 1043, 0, False, 'xvi', 43))
    list_palabras.append(Palabra('responsables', 'ADJ', 'obj', 14, 1048, 0, False, 'responsable', 48))
    list_palabras.append(Palabra('Inquisición', 'PROPN', 'nmod', 15, 1075, 0, False, 'Inquisición', 75))
    list_relaciones.append(Relacion('gobernaron', Palabra.palabras_dict.get('Austrias-4') , Palabra.palabras_dict.get('España-24'), position_doc=13 , lugar_sintactico='obj', importancia = 2028, id=-10))
    list_relaciones.append(Relacion('gobernaron', Palabra.palabras_dict.get('Austrias-4') , Palabra.palabras_dict.get('siglo-37'), position_doc=13 , lugar_sintactico='obl', importancia = 2041, id=-11))
    list_relaciones.append(Relacion('gobernaron', Palabra.palabras_dict.get('Austrias-4') , Palabra.palabras_dict.get('responsable-48'), position_doc=13 , lugar_sintactico='obj', importancia = 2052, id=-12))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('siglo-37') , Palabra.palabras_dict.get('xvi-43'), position_doc=31 , lugar_sintactico='compound', importancia = 2080, id=-13))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('siglo-37') , Palabra.palabras_dict.get('xvi-43'), position_doc=34 , lugar_sintactico='compound', importancia = 2080, id=-14))
    list_relaciones.append(Relacion('también', Palabra.palabras_dict.get('responsable-48') , Palabra.palabras_dict.get('Inquisición-75'), position_doc=61 , lugar_sintactico='nmod', importancia = 2123, id=-15))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('responsable-48') , Palabra.palabras_dict.get('Inquisición-75'), position_doc=69 , lugar_sintactico='nmod', importancia = 2123, id=-22))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('responsable-48') , Palabra.palabras_dict.get('Inquisición-75'), position_doc=72 , lugar_sintactico='nmod', importancia = 2123, id=-23))
    return list_palabras, list_relaciones

def test2():
    list_palabras = []
    list_relaciones= []
    list_palabras.append(Palabra('Austrias', 'PROPN', 'nsubj', 10, 1004, 0, False, 'Austrias', 4))
    list_palabras.append(Palabra('España', 'PROPN', 'obj', 11, 1024, 0, False, 'España', 24))
    list_palabras.append(Palabra('siglo', 'NOUN', 'obl', 12, 1037, 0, False, 'siglo', 37))
    list_palabras.append(Palabra('XVI', 'NOUN', 'compound', 13, 1043, 0, False, 'xvi', 43))
    list_palabras.append(Palabra('XVII', 'NOUN', 'conj', 14, 1049, 0, False, 'xvii', 49))
    list_palabras.append(Palabra('responsables', 'ADJ', 'obj', 15, 1055, 0, False, 'responsable', 55))
    list_palabras.append(Palabra('Inquisición', 'PROPN', 'nmod', 16, 1082, 0, False, 'Inquisición', 82))
    list_palabras.append(Palabra('expulsión', 'NOUN', 'obj', 17, 1095, 0, False, 'expulsión', 95))
    list_palabras.append(Palabra('judíos', 'NOUN', 'nmod', 18, 1108, 0, False, 'judío', 108))
    list_palabras.append(Palabra('legado', 'NOUN', 'ROOT', 19, 1119, 0, False, 'legado', 119))
    list_palabras.append(Palabra('arquitectura', 'NOUN', 'appos', 20, 1127, 0, False, 'arquitectura', 127))
    list_palabras.append(Palabra('arte', 'NOUN', 'conj', 21, 1142, 0, False, 'arte', 142))
    list_palabras.append(Palabra('Madrid', 'PROPN', 'nmod', 22, 1150, 0, False, 'Madrid', 150))
    list_palabras.append(Palabra('Córdoba', 'PROPN', 'conj', 23, 1159, 0, False, 'Córdoba', 159))
    list_relaciones.append(Relacion('gobernaron', Palabra.palabras_dict.get('Austrias-4') , Palabra.palabras_dict.get('España-24'), position_doc=13 , lugar_sintactico='obj', importancia = 2028, id=-10))
    list_relaciones.append(Relacion('gobernaron', Palabra.palabras_dict.get('Austrias-4') , Palabra.palabras_dict.get('siglo-37'), position_doc=13 , lugar_sintactico='obl', importancia = 2041, id=-11))
    list_relaciones.append(Relacion('gobernaron', Palabra.palabras_dict.get('Austrias-4') , Palabra.palabras_dict.get('responsable-55'), position_doc=13 , lugar_sintactico='obj', importancia = 2059, id=-12))
    list_relaciones.append(Relacion('gobernaron', Palabra.palabras_dict.get('Austrias-4') , Palabra.palabras_dict.get('expulsión-95'), position_doc=13 , lugar_sintactico='obj', importancia = 2099, id=-13))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('siglo-37') , Palabra.palabras_dict.get('xvi-43'), position_doc=31 , lugar_sintactico='compound', importancia = 2080, id=-14))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('siglo-37') , Palabra.palabras_dict.get('xvii-49'), position_doc=31 , lugar_sintactico='conj', importancia = 2086, id=-15))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('siglo-37') , Palabra.palabras_dict.get('xvi-43'), position_doc=34 , lugar_sintactico='compound', importancia = 2080, id=-16))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('siglo-37') , Palabra.palabras_dict.get('xvii-49'), position_doc=34 , lugar_sintactico='conj', importancia = 2086, id=-17))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('siglo-37') , Palabra.palabras_dict.get('xvii-49'), position_doc=47 , lugar_sintactico='conj', importancia = 2086, id=-18))
    list_relaciones.append(Relacion('también', Palabra.palabras_dict.get('responsable-55') , Palabra.palabras_dict.get('Inquisición-82'), position_doc=68 , lugar_sintactico='nmod', importancia = 2137, id=-19))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('expulsión-95') , Palabra.palabras_dict.get('judío-108'), position_doc=105 , lugar_sintactico='nmod', importancia = 2203, id=-20))
    list_relaciones.append(Relacion('su', Palabra.palabras_dict.get('legado-119') , Palabra.palabras_dict.get('arquitectura-127'), position_doc=116 , lugar_sintactico='appos', importancia = 2246, id=-21))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('arquitectura-127') , Palabra.palabras_dict.get('arte-142'), position_doc=140 , lugar_sintactico='conj', importancia = 2269, id=-22))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('arquitectura-127') , Palabra.palabras_dict.get('Madrid-150'), position_doc=147 , lugar_sintactico='nmod', importancia = 2277, id=-23))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('arquitectura-127') , Palabra.palabras_dict.get('Córdoba-159'), position_doc=147 , lugar_sintactico='conj', importancia = 2286, id=-24))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('Madrid-150') , Palabra.palabras_dict.get('Córdoba-159'), position_doc=157 , lugar_sintactico='conj', importancia = 2309, id=-25))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('responsable-55') , Palabra.palabras_dict.get('Inquisición-82'), position_doc=76 , lugar_sintactico='nmod', importancia = 2137, id=-36))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('responsable-55') , Palabra.palabras_dict.get('Inquisición-82'), position_doc=79 , lugar_sintactico='nmod', importancia = 2137, id=-37))
    return list_palabras, list_relaciones

def test3():
    list_palabras = []
    list_relaciones= []
    list_palabras.append(Palabra('Austrias', 'PROPN', 'nsubj', 10, 1004, 0, False, 'Austrias', 4))
    list_palabras.append(Palabra('España', 'PROPN', 'obj', 11, 1024, 0, False, 'España', 24))
    list_palabras.append(Palabra('siglo', 'NOUN', 'obl', 12, 1037, 0, False, 'siglo', 37))
    list_palabras.append(Palabra('XVI', 'NOUN', 'compound', 13, 1043, 0, False, 'xvi', 43))
    list_palabras.append(Palabra('XVII', 'NOUN', 'conj', 14, 1049, 0, False, 'xvii', 49))
    list_palabras.append(Palabra('territorio', 'NOUN', 'obj', 15, 1068, 0, False, 'territorio', 68))
    list_palabras.append(Palabra('responsables', 'ADJ', 'conj', 16, 1092, 0, False, 'responsable', 92))
    list_palabras.append(Palabra('Inquisición', 'PROPN', 'nmod', 17, 1111, 0, False, 'Inquisición', 111))
    list_palabras.append(Palabra('expulsión', 'NOUN', 'conj', 18, 1128, 0, False, 'expulsión', 128))
    list_palabras.append(Palabra('judíos', 'NOUN', 'nmod', 19, 1141, 0, False, 'judío', 141))
    list_palabras.append(Palabra('legado', 'NOUN', 'nsubj', 20, 1152, 0, False, 'legado', 152))
    list_palabras.append(Palabra('arquitectura', 'NOUN', 'obl', 21, 1171, 0, False, 'arquitectura', 171))
    list_palabras.append(Palabra('arte', 'NOUN', 'conj', 22, 1189, 0, False, 'arte', 189))
    list_palabras.append(Palabra('Madrid', 'PROPN', 'nmod', 23, 1212, 0, False, 'Madrid', 212))
    list_palabras.append(Palabra('Granada', 'PROPN', 'conj', 24, 1220, 0, False, 'Granada', 220))
    list_palabras.append(Palabra('Córdoba', 'PROPN', 'conj', 25, 1230, 0, False, 'Córdoba', 230))
    list_relaciones.append(Relacion('gobernaron', Palabra.palabras_dict.get('Austrias-4') , Palabra.palabras_dict.get('España-24'), position_doc=13 , lugar_sintactico='obj', importancia = 2028, id=-10))
    list_relaciones.append(Relacion('gobernaron', Palabra.palabras_dict.get('Austrias-4') , Palabra.palabras_dict.get('siglo-37'), position_doc=13 , lugar_sintactico='obl', importancia = 2041, id=-11))
    list_relaciones.append(Relacion('gobernaron', Palabra.palabras_dict.get('Austrias-4') , Palabra.palabras_dict.get('responsable-92'), position_doc=13 , lugar_sintactico='conj', importancia = 2096, id=-12))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('siglo-37') , Palabra.palabras_dict.get('xvi-43'), position_doc=31 , lugar_sintactico='compound', importancia = 2080, id=-13))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('siglo-37') , Palabra.palabras_dict.get('xvii-49'), position_doc=31 , lugar_sintactico='conj', importancia = 2086, id=-14))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('siglo-37') , Palabra.palabras_dict.get('xvi-43'), position_doc=34 , lugar_sintactico='compound', importancia = 2080, id=-15))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('siglo-37') , Palabra.palabras_dict.get('xvii-49'), position_doc=34 , lugar_sintactico='conj', importancia = 2086, id=-16))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('siglo-37') , Palabra.palabras_dict.get('xvii-49'), position_doc=47 , lugar_sintactico='conj', importancia = 2086, id=-17))
    list_relaciones.append(Relacion('pero', Palabra.palabras_dict.get('responsable-92') , Palabra.palabras_dict.get('Inquisición-111'), position_doc=79 , lugar_sintactico='nmod', importancia = 2203, id=-18))
    list_relaciones.append(Relacion('pero', Palabra.palabras_dict.get('responsable-92') , Palabra.palabras_dict.get('expulsión-128'), position_doc=79 , lugar_sintactico='conj', importancia = 2220, id=-19))
    list_relaciones.append(Relacion('también', Palabra.palabras_dict.get('responsable-92') , Palabra.palabras_dict.get('Inquisición-111'), position_doc=84 , lugar_sintactico='nmod', importancia = 2203, id=-20))
    list_relaciones.append(Relacion('también', Palabra.palabras_dict.get('responsable-92') , Palabra.palabras_dict.get('expulsión-128'), position_doc=84 , lugar_sintactico='conj', importancia = 2220, id=-21))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('responsable-92') , Palabra.palabras_dict.get('Inquisición-111'), position_doc=105 , lugar_sintactico='nmod', importancia = 2203, id=-22))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('responsable-92') , Palabra.palabras_dict.get('Inquisición-111'), position_doc=108 , lugar_sintactico='nmod', importancia = 2203, id=-23))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('responsable-92') , Palabra.palabras_dict.get('expulsión-128'), position_doc=123 , lugar_sintactico='conj', importancia = 2220, id=-24))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('responsable-92') , Palabra.palabras_dict.get('judío-141'), position_doc=123 , lugar_sintactico='nmod', importancia = 2233, id=-25))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('responsable-92') , Palabra.palabras_dict.get('expulsión-128'), position_doc=125 , lugar_sintactico='conj', importancia = 2220, id=-26))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('responsable-92') , Palabra.palabras_dict.get('judío-141'), position_doc=125 , lugar_sintactico='nmod', importancia = 2233, id=-27))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('expulsión-128') , Palabra.palabras_dict.get('judío-141'), position_doc=138 , lugar_sintactico='nmod', importancia = 2269, id=-28))
    list_relaciones.append(Relacion('ve', Palabra.palabras_dict.get('legado-152') , Palabra.palabras_dict.get('arquitectura-171'), position_doc=162 , lugar_sintactico='obl', importancia = 2323, id=-29))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('arquitectura-171') , Palabra.palabras_dict.get('arte-189'), position_doc=165 , lugar_sintactico='conj', importancia = 2360, id=-30))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('arquitectura-171') , Palabra.palabras_dict.get('arte-189'), position_doc=168 , lugar_sintactico='conj', importancia = 2360, id=-31))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('arquitectura-171') , Palabra.palabras_dict.get('arte-189'), position_doc=184 , lugar_sintactico='conj', importancia = 2360, id=-32))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('arquitectura-171') , Palabra.palabras_dict.get('arte-189'), position_doc=186 , lugar_sintactico='conj', importancia = 2360, id=-33))
    list_relaciones.append(Relacion('especialmente', Palabra.palabras_dict.get('Madrid-212') , Palabra.palabras_dict.get('Granada-220'), position_doc=195 , lugar_sintactico='conj', importancia = 2432, id=-34))
    list_relaciones.append(Relacion('especialmente', Palabra.palabras_dict.get('Madrid-212') , Palabra.palabras_dict.get('Córdoba-230'), position_doc=195 , lugar_sintactico='conj', importancia = 2442, id=-35))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('Madrid-212') , Palabra.palabras_dict.get('Córdoba-230'), position_doc=228 , lugar_sintactico='conj', importancia = 2442, id=-36))
    return list_palabras, list_relaciones
def test4():
    list_palabras = []
    list_relaciones= []
    list_palabras.append(Palabra('dinastía', 'NOUN', 'nsubj', 10, 1003, 0, False, 'dinastía', 3))
    list_palabras.append(Palabra('Austrias', 'PROPN', 'nmod', 11, 1019, 0, False, 'Austrias', 19))
    list_palabras.append(Palabra('España', 'PROPN', 'obj', 12, 1036, 0, False, 'España', 36))
    list_palabras.append(Palabra('siglo', 'NOUN', 'obl', 13, 1052, 0, False, 'siglo', 52))
    list_palabras.append(Palabra('XVI', 'NOUN', 'compound', 14, 1058, 0, False, 'xvi', 58))
    list_palabras.append(Palabra('siglo', 'NOUN', 'obl', 15, 1071, 0, False, 'siglo', 71))
    list_palabras.append(Palabra('XVII', 'NOUN', 'compound', 16, 1077, 0, False, 'xvii', 77))
    list_palabras.append(Palabra('reinado', 'NOUN', 'obl', 17, 1094, 0, False, 'reinado', 94))
    list_palabras.append(Palabra('país', 'NOUN', 'nsubj', 18, 1106, 0, False, 'país', 106))
    list_palabras.append(Palabra('época', 'NOUN', 'obj', 19, 1127, 0, False, 'época', 127))
    list_palabras.append(Palabra('esplendor', 'NOUN', 'nmod', 20, 1136, 0, False, 'esplendor', 136))
    list_palabras.append(Palabra('decadencia', 'NOUN', 'conj', 21, 1148, 0, False, 'decadencia', 148))
    list_palabras.append(Palabra('monarcas', 'NOUN', 'nsubj', 22, 1164, 0, False, 'monarca', 164))
    list_palabras.append(Palabra('austriacos', 'ADJ', 'amod', 23, 1173, 0, False, 'austriaco', 173))
    list_palabras.append(Palabra('Carlos', 'PROPN', 'appos', 24, 1197, 0, False, 'Carlos', 197))
    list_palabras.append(Palabra('I', 'PROPN', 'flat', 25, 1204, 0, False, 'I', 204))
    list_palabras.append(Palabra('Felipe', 'PROPN', 'conj', 26, 1208, 0, False, 'Felipe', 208))
    list_palabras.append(Palabra('II', 'PROPN', 'flat', 27, 1215, 0, False, 'II', 215))
    list_palabras.append(Palabra('territorio', 'NOUN', 'obj', 28, 1232, 0, False, 'territorio', 232))
    list_palabras.append(Palabra('español', 'ADJ', 'amod', 29, 1243, 0, False, 'español', 243))
    list_palabras.append(Palabra('conquista', 'NOUN', 'obl', 30, 1263, 0, False, 'conquista', 263))
    list_palabras.append(Palabra('América', 'PROPN', 'nmod', 31, 1276, 0, False, 'América', 276))
    list_palabras.append(Palabra('anexión', 'NOUN', 'conj', 32, 1289, 0, False, 'anexión', 289))
    list_palabras.append(Palabra('Portugal', 'PROPN', 'nmod', 33, 1300, 0, False, 'Portugal', 300))
    list_palabras.append(Palabra('embargo', 'NOUN', 'fixed', 34, 1314, 0, False, 'embargo', 314))
    list_palabras.append(Palabra('fueron', 'AUX', 'cop', 35, 1331, 0, False, 'ser', 331))
    list_palabras.append(Palabra('responsables', 'NOUN', 'ROOT', 36, 1338, 0, False, 'responsable', 338))
    list_palabras.append(Palabra('Inquisición', 'PROPN', 'nmod', 37, 1357, 0, False, 'Inquisición', 357))
    list_palabras.append(Palabra('española', 'ADJ', 'amod', 38, 1369, 0, False, 'español', 369))
    list_palabras.append(Palabra('expulsión', 'NOUN', 'conj', 39, 1386, 0, False, 'expulsión', 386))
    list_palabras.append(Palabra('judíos', 'NOUN', 'nmod', 40, 1403, 0, False, 'judío', 403))
    list_palabras.append(Palabra('falta', 'NOUN', 'nsubj', 41, 1414, 0, False, 'falta', 414))
    list_palabras.append(Palabra('recursos', 'NOUN', 'nmod', 42, 1423, 0, False, 'recurso', 423))
    list_palabras.append(Palabra('guerras', 'NOUN', 'conj', 43, 1438, 0, False, 'guerra', 438))
    list_palabras.append(Palabra('Europa', 'PROPN', 'nmod', 44, 1449, 0, False, 'Europa', 449))
    list_palabras.append(Palabra('declive', 'NOUN', 'obj', 45, 1473, 0, False, 'declive', 473))
    list_palabras.append(Palabra('monarquía', 'NOUN', 'nmod', 46, 1487, 0, False, 'monarquía', 487))
    list_palabras.append(Palabra('llegada', 'NOUN', 'obl', 47, 1517, 0, False, 'llegada', 517))
    list_palabras.append(Palabra('dinastía', 'NOUN', 'nmod', 48, 1531, 0, False, 'dinastía', 531))
    list_palabras.append(Palabra('Borbones', 'PROPN', 'nmod', 49, 1547, 0, False, 'Borbones', 547))
    list_palabras.append(Palabra('siglo', 'NOUN', 'nmod', 50, 1562, 0, False, 'siglo', 562))
    list_palabras.append(Palabra('XVIII', 'NOUN', 'compound', 51, 1568, 0, False, 'xviii', 568))
    list_palabras.append(Palabra('legado', 'NOUN', 'nsubj', 52, 1578, 0, False, 'legado', 578))
    list_palabras.append(Palabra('Austrias', 'PROPN', 'nmod', 53, 1592, 0, False, 'Austrias', 592))
    list_palabras.append(Palabra('España', 'PROPN', 'nmod', 54, 1604, 0, False, 'España', 604))
    list_palabras.append(Palabra('puede', 'AUX', 'aux', 55, 1614, 0, False, 'poder', 614))
    list_palabras.append(Palabra('arquitectura', 'NOUN', 'obl', 56, 1630, 0, False, 'arquitectura', 630))
    list_palabras.append(Palabra('arte', 'NOUN', 'conj', 57, 1645, 0, False, 'arte', 645))
    list_palabras.append(Palabra('Madrid', 'PROPN', 'nmod', 58, 1668, 0, False, 'Madrid', 668))
    list_palabras.append(Palabra('ciudades', 'NOUN', 'conj', 59, 1684, 0, False, 'ciudad', 684))
    list_palabras.append(Palabra('andaluzas', 'NOUN', 'amod', 60, 1693, 0, False, 'andaluza', 693))
    list_palabras.append(Palabra('Granada', 'PROPN', 'nmod', 61, 1706, 0, False, 'Granada', 706))
    list_palabras.append(Palabra('Córdoba', 'PROPN', 'conj', 62, 1716, 0, False, 'Córdoba', 716))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('dinastía-3') , Palabra.palabras_dict.get('Austrias-19'), position_doc=0 , lugar_sintactico='nmod', importancia = 2022, id=-10))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('dinastía-3') , Palabra.palabras_dict.get('Austrias-19'), position_doc=12 , lugar_sintactico='nmod', importancia = 2022, id=-11))
    list_relaciones.append(Relacion('los', Palabra.palabras_dict.get('dinastía-3') , Palabra.palabras_dict.get('Austrias-19'), position_doc=15 , lugar_sintactico='nmod', importancia = 2022, id=-12))
    list_relaciones.append(Relacion('gobernó', Palabra.palabras_dict.get('dinastía-3') , Palabra.palabras_dict.get('España-36'), position_doc=28 , lugar_sintactico='obj', importancia = 2039, id=-13))
    list_relaciones.append(Relacion('gobernó', Palabra.palabras_dict.get('dinastía-3') , Palabra.palabras_dict.get('siglo-52'), position_doc=28 , lugar_sintactico='obl', importancia = 2055, id=-14))
    list_relaciones.append(Relacion('gobernó', Palabra.palabras_dict.get('dinastía-3') , Palabra.palabras_dict.get('siglo-71'), position_doc=28 , lugar_sintactico='obl', importancia = 2074, id=-15))
    list_relaciones.append(Relacion('desde', Palabra.palabras_dict.get('siglo-52') , Palabra.palabras_dict.get('xvi-58'), position_doc=43 , lugar_sintactico='compound', importancia = 2110, id=-16))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('siglo-52') , Palabra.palabras_dict.get('xvi-58'), position_doc=49 , lugar_sintactico='compound', importancia = 2110, id=-17))
    list_relaciones.append(Relacion('hasta', Palabra.palabras_dict.get('siglo-71') , Palabra.palabras_dict.get('xvii-77'), position_doc=62 , lugar_sintactico='compound', importancia = 2148, id=-18))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('siglo-71') , Palabra.palabras_dict.get('xvii-77'), position_doc=68 , lugar_sintactico='compound', importancia = 2148, id=-19))
    list_relaciones.append(Relacion('experimentó', Palabra.palabras_dict.get('reinado-94') , Palabra.palabras_dict.get('país-106'), position_doc=111 , lugar_sintactico='nsubj', importancia = 2200, id=-20))
    list_relaciones.append(Relacion('experimentó', Palabra.palabras_dict.get('reinado-94') , Palabra.palabras_dict.get('época-127'), position_doc=111 , lugar_sintactico='obj', importancia = 2221, id=-21))
    list_relaciones.append(Relacion('una', Palabra.palabras_dict.get('época-127') , Palabra.palabras_dict.get('esplendor-136'), position_doc=123 , lugar_sintactico='nmod', importancia = 2263, id=-22))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('época-127') , Palabra.palabras_dict.get('esplendor-136'), position_doc=133 , lugar_sintactico='nmod', importancia = 2263, id=-23))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('época-127') , Palabra.palabras_dict.get('decadencia-148'), position_doc=133 , lugar_sintactico='conj', importancia = 2275, id=-24))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('esplendor-136') , Palabra.palabras_dict.get('decadencia-148'), position_doc=146 , lugar_sintactico='conj', importancia = 2284, id=-25))
    list_relaciones.append(Relacion('los', Palabra.palabras_dict.get('monarca-164') , Palabra.palabras_dict.get('austriaco-173'), position_doc=160 , lugar_sintactico='amod', importancia = 2337, id=-26))
    list_relaciones.append(Relacion('entre', Palabra.palabras_dict.get('monarca-164') , Palabra.palabras_dict.get('austriaco-173'), position_doc=185 , lugar_sintactico='amod', importancia = 2337, id=-27))
    list_relaciones.append(Relacion('ellos', Palabra.palabras_dict.get('monarca-164') , Palabra.palabras_dict.get('Carlos-197'), position_doc=191 , lugar_sintactico='appos', importancia = 2361, id=-28))
    list_relaciones.append(Relacion('ellos', Palabra.palabras_dict.get('monarca-164') , Palabra.palabras_dict.get('austriaco-173'), position_doc=191 , lugar_sintactico='amod', importancia = 2337, id=-29))
    list_relaciones.append(Relacion('ellos', Palabra.palabras_dict.get('monarca-164') , Palabra.palabras_dict.get('I-204'), position_doc=191 , lugar_sintactico='flat', importancia = 2368, id=-30))
    list_relaciones.append(Relacion('ellos', Palabra.palabras_dict.get('monarca-164') , Palabra.palabras_dict.get('Felipe-208'), position_doc=191 , lugar_sintactico='conj', importancia = 2372, id=-31))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('Carlos-197') , Palabra.palabras_dict.get('Felipe-208'), position_doc=206 , lugar_sintactico='conj', importancia = 2405, id=-32))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('Carlos-197') , Palabra.palabras_dict.get('II-215'), position_doc=206 , lugar_sintactico='flat', importancia = 2412, id=-33))
    list_relaciones.append(Relacion('ampliaron', Palabra.palabras_dict.get('monarca-164') , Palabra.palabras_dict.get('territorio-232'), position_doc=219 , lugar_sintactico='obj', importancia = 2396, id=-34))
    list_relaciones.append(Relacion('ampliaron', Palabra.palabras_dict.get('monarca-164') , Palabra.palabras_dict.get('conquista-263'), position_doc=219 , lugar_sintactico='obl', importancia = 2427, id=-35))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('territorio-232') , Palabra.palabras_dict.get('español-243'), position_doc=229 , lugar_sintactico='amod', importancia = 2475, id=-36))
    list_relaciones.append(Relacion('mediante', Palabra.palabras_dict.get('conquista-263') , Palabra.palabras_dict.get('América-276'), position_doc=251 , lugar_sintactico='nmod', importancia = 2539, id=-37))
    list_relaciones.append(Relacion('mediante', Palabra.palabras_dict.get('conquista-263') , Palabra.palabras_dict.get('anexión-289'), position_doc=251 , lugar_sintactico='conj', importancia = 2552, id=-38))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('conquista-263') , Palabra.palabras_dict.get('América-276'), position_doc=260 , lugar_sintactico='nmod', importancia = 2539, id=-39))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('conquista-263') , Palabra.palabras_dict.get('anexión-289'), position_doc=260 , lugar_sintactico='conj', importancia = 2552, id=-40))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('conquista-263') , Palabra.palabras_dict.get('América-276'), position_doc=273 , lugar_sintactico='nmod', importancia = 2539, id=-41))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('conquista-263') , Palabra.palabras_dict.get('anexión-289'), position_doc=284 , lugar_sintactico='conj', importancia = 2552, id=-42))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('conquista-263') , Palabra.palabras_dict.get('Portugal-300'), position_doc=284 , lugar_sintactico='nmod', importancia = 2563, id=-43))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('conquista-263') , Palabra.palabras_dict.get('anexión-289'), position_doc=286 , lugar_sintactico='conj', importancia = 2552, id=-44))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('conquista-263') , Palabra.palabras_dict.get('Portugal-300'), position_doc=286 , lugar_sintactico='nmod', importancia = 2563, id=-45))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('anexión-289') , Palabra.palabras_dict.get('Portugal-300'), position_doc=297 , lugar_sintactico='nmod', importancia = 2589, id=-46))
    list_relaciones.append(Relacion('sin', Palabra.palabras_dict.get('embargo-314') , Palabra.palabras_dict.get('responsable-338'), position_doc=310 , lugar_sintactico='ROOT', importancia = 2652, id=-47))
    list_relaciones.append(Relacion('sin', Palabra.palabras_dict.get('embargo-314') , Palabra.palabras_dict.get('ser-331'), position_doc=310 , lugar_sintactico='cop', importancia = 2645, id=-48))
    list_relaciones.append(Relacion('sin', Palabra.palabras_dict.get('embargo-314') , Palabra.palabras_dict.get('Inquisición-357'), position_doc=310 , lugar_sintactico='nmod', importancia = 2671, id=-49))
    list_relaciones.append(Relacion('también', Palabra.palabras_dict.get('ser-331') , Palabra.palabras_dict.get('responsable-338'), position_doc=323 , lugar_sintactico='ROOT', importancia = 2669, id=-50))
    list_relaciones.append(Relacion('también', Palabra.palabras_dict.get('ser-331') , Palabra.palabras_dict.get('Inquisición-357'), position_doc=323 , lugar_sintactico='nmod', importancia = 2688, id=-51))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('responsable-338') , Palabra.palabras_dict.get('Inquisición-357'), position_doc=351 , lugar_sintactico='nmod', importancia = 2695, id=-52))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('responsable-338') , Palabra.palabras_dict.get('español-369'), position_doc=351 , lugar_sintactico='amod', importancia = 2707, id=-53))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('responsable-338') , Palabra.palabras_dict.get('expulsión-386'), position_doc=351 , lugar_sintactico='conj', importancia = 2724, id=-54))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('responsable-338') , Palabra.palabras_dict.get('Inquisición-357'), position_doc=354 , lugar_sintactico='nmod', importancia = 2695, id=-55))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('responsable-338') , Palabra.palabras_dict.get('español-369'), position_doc=354 , lugar_sintactico='amod', importancia = 2707, id=-56))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('responsable-338') , Palabra.palabras_dict.get('expulsión-386'), position_doc=354 , lugar_sintactico='conj', importancia = 2724, id=-57))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('Inquisición-357') , Palabra.palabras_dict.get('expulsión-386'), position_doc=378 , lugar_sintactico='conj', importancia = 2743, id=-58))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('Inquisición-357') , Palabra.palabras_dict.get('judío-403'), position_doc=378 , lugar_sintactico='nmod', importancia = 2760, id=-59))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('Inquisición-357') , Palabra.palabras_dict.get('expulsión-386'), position_doc=380 , lugar_sintactico='conj', importancia = 2743, id=-60))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('Inquisición-357') , Palabra.palabras_dict.get('judío-403'), position_doc=380 , lugar_sintactico='nmod', importancia = 2760, id=-61))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('Inquisición-357') , Palabra.palabras_dict.get('expulsión-386'), position_doc=383 , lugar_sintactico='conj', importancia = 2743, id=-62))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('Inquisición-357') , Palabra.palabras_dict.get('judío-403'), position_doc=383 , lugar_sintactico='nmod', importancia = 2760, id=-63))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('expulsión-386') , Palabra.palabras_dict.get('judío-403'), position_doc=396 , lugar_sintactico='nmod', importancia = 2789, id=-64))
    list_relaciones.append(Relacion('los', Palabra.palabras_dict.get('expulsión-386') , Palabra.palabras_dict.get('judío-403'), position_doc=399 , lugar_sintactico='nmod', importancia = 2789, id=-65))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('falta-414') , Palabra.palabras_dict.get('recurso-423'), position_doc=411 , lugar_sintactico='nmod', importancia = 2837, id=-66))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('falta-414') , Palabra.palabras_dict.get('guerra-438'), position_doc=411 , lugar_sintactico='conj', importancia = 2852, id=-67))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('falta-414') , Palabra.palabras_dict.get('recurso-423'), position_doc=420 , lugar_sintactico='nmod', importancia = 2837, id=-68))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('falta-414') , Palabra.palabras_dict.get('guerra-438'), position_doc=432 , lugar_sintactico='conj', importancia = 2852, id=-69))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('falta-414') , Palabra.palabras_dict.get('Europa-449'), position_doc=432 , lugar_sintactico='nmod', importancia = 2863, id=-70))
    list_relaciones.append(Relacion('las', Palabra.palabras_dict.get('falta-414') , Palabra.palabras_dict.get('guerra-438'), position_doc=434 , lugar_sintactico='conj', importancia = 2852, id=-71))
    list_relaciones.append(Relacion('las', Palabra.palabras_dict.get('falta-414') , Palabra.palabras_dict.get('Europa-449'), position_doc=434 , lugar_sintactico='nmod', importancia = 2863, id=-72))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('guerra-438') , Palabra.palabras_dict.get('Europa-449'), position_doc=446 , lugar_sintactico='nmod', importancia = 2887, id=-73))
    list_relaciones.append(Relacion('contribuyeron', Palabra.palabras_dict.get('falta-414') , Palabra.palabras_dict.get('declive-473'), position_doc=456 , lugar_sintactico='obj', importancia = 2887, id=-74))
    list_relaciones.append(Relacion('al', Palabra.palabras_dict.get('declive-473') , Palabra.palabras_dict.get('monarquía-487'), position_doc=470 , lugar_sintactico='nmod', importancia = 2960, id=-75))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('declive-473') , Palabra.palabras_dict.get('monarquía-487'), position_doc=481 , lugar_sintactico='nmod', importancia = 2960, id=-76))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('declive-473') , Palabra.palabras_dict.get('monarquía-487'), position_doc=484 , lugar_sintactico='nmod', importancia = 2960, id=-77))
    list_relaciones.append(Relacion('que', Palabra.palabras_dict.get('declive-473') , Palabra.palabras_dict.get('monarquía-487'), position_doc=498 , lugar_sintactico='nmod', importancia = 2960, id=-78))
    list_relaciones.append(Relacion('terminó', Palabra.palabras_dict.get('declive-473') , Palabra.palabras_dict.get('llegada-517'), position_doc=502 , lugar_sintactico='obl', importancia = 2990, id=-79))
    list_relaciones.append(Relacion('terminó', Palabra.palabras_dict.get('declive-473') , Palabra.palabras_dict.get('monarquía-487'), position_doc=502 , lugar_sintactico='nmod', importancia = 2960, id=-80))
    list_relaciones.append(Relacion('terminó', Palabra.palabras_dict.get('declive-473') , Palabra.palabras_dict.get('dinastía-531'), position_doc=502 , lugar_sintactico='nmod', importancia = 3004, id=-81))
    list_relaciones.append(Relacion('terminó', Palabra.palabras_dict.get('declive-473') , Palabra.palabras_dict.get('siglo-562'), position_doc=502 , lugar_sintactico='nmod', importancia = 3035, id=-82))
    list_relaciones.append(Relacion('con', Palabra.palabras_dict.get('llegada-517') , Palabra.palabras_dict.get('dinastía-531'), position_doc=510 , lugar_sintactico='nmod', importancia = 3048, id=-83))
    list_relaciones.append(Relacion('con', Palabra.palabras_dict.get('llegada-517') , Palabra.palabras_dict.get('siglo-562'), position_doc=510 , lugar_sintactico='nmod', importancia = 3079, id=-84))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('llegada-517') , Palabra.palabras_dict.get('dinastía-531'), position_doc=514 , lugar_sintactico='nmod', importancia = 3048, id=-85))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('llegada-517') , Palabra.palabras_dict.get('siglo-562'), position_doc=514 , lugar_sintactico='nmod', importancia = 3079, id=-86))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('llegada-517') , Palabra.palabras_dict.get('dinastía-531'), position_doc=525 , lugar_sintactico='nmod', importancia = 3048, id=-87))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('llegada-517') , Palabra.palabras_dict.get('Borbones-547'), position_doc=525 , lugar_sintactico='nmod', importancia = 3064, id=-88))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('llegada-517') , Palabra.palabras_dict.get('dinastía-531'), position_doc=528 , lugar_sintactico='nmod', importancia = 3048, id=-89))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('llegada-517') , Palabra.palabras_dict.get('Borbones-547'), position_doc=528 , lugar_sintactico='nmod', importancia = 3064, id=-90))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('dinastía-531') , Palabra.palabras_dict.get('Borbones-547'), position_doc=540 , lugar_sintactico='nmod', importancia = 3078, id=-91))
    list_relaciones.append(Relacion('los', Palabra.palabras_dict.get('dinastía-531') , Palabra.palabras_dict.get('Borbones-547'), position_doc=543 , lugar_sintactico='nmod', importancia = 3078, id=-92))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('llegada-517') , Palabra.palabras_dict.get('siglo-562'), position_doc=556 , lugar_sintactico='nmod', importancia = 3079, id=-93))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('llegada-517') , Palabra.palabras_dict.get('xviii-568'), position_doc=556 , lugar_sintactico='compound', importancia = 3085, id=-94))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('llegada-517') , Palabra.palabras_dict.get('siglo-562'), position_doc=559 , lugar_sintactico='nmod', importancia = 3079, id=-95))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('llegada-517') , Palabra.palabras_dict.get('xviii-568'), position_doc=559 , lugar_sintactico='compound', importancia = 3085, id=-96))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('legado-578') , Palabra.palabras_dict.get('Austrias-592'), position_doc=575 , lugar_sintactico='nmod', importancia = 3170, id=-97))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('legado-578') , Palabra.palabras_dict.get('España-604'), position_doc=575 , lugar_sintactico='nmod', importancia = 3182, id=-98))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('legado-578') , Palabra.palabras_dict.get('Austrias-592'), position_doc=585 , lugar_sintactico='nmod', importancia = 3170, id=-99))
    list_relaciones.append(Relacion('los', Palabra.palabras_dict.get('legado-578') , Palabra.palabras_dict.get('Austrias-592'), position_doc=588 , lugar_sintactico='nmod', importancia = 3170, id=-100))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('legado-578') , Palabra.palabras_dict.get('España-604'), position_doc=601 , lugar_sintactico='nmod', importancia = 3182, id=-101))
    list_relaciones.append(Relacion('ver', Palabra.palabras_dict.get('legado-578') , Palabra.palabras_dict.get('poder-614'), position_doc=620 , lugar_sintactico='aux', importancia = 3192, id=-102))
    list_relaciones.append(Relacion('ver', Palabra.palabras_dict.get('legado-578') , Palabra.palabras_dict.get('arquitectura-630'), position_doc=620 , lugar_sintactico='obl', importancia = 3208, id=-103))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('arquitectura-630') , Palabra.palabras_dict.get('arte-645'), position_doc=624 , lugar_sintactico='conj', importancia = 3275, id=-104))
    list_relaciones.append(Relacion('su', Palabra.palabras_dict.get('arquitectura-630') , Palabra.palabras_dict.get('arte-645'), position_doc=627 , lugar_sintactico='conj', importancia = 3275, id=-105))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('arquitectura-630') , Palabra.palabras_dict.get('arte-645'), position_doc=643 , lugar_sintactico='conj', importancia = 3275, id=-106))
    list_relaciones.append(Relacion('especialmente', Palabra.palabras_dict.get('Madrid-668') , Palabra.palabras_dict.get('ciudad-684'), position_doc=651 , lugar_sintactico='conj', importancia = 3352, id=-107))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('ciudad-684') , Palabra.palabras_dict.get('andaluza-693'), position_doc=675 , lugar_sintactico='amod', importancia = 3377, id=-108))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('ciudad-684') , Palabra.palabras_dict.get('Granada-706'), position_doc=675 , lugar_sintactico='nmod', importancia = 3390, id=-109))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('ciudad-684') , Palabra.palabras_dict.get('andaluza-693'), position_doc=677 , lugar_sintactico='amod', importancia = 3377, id=-110))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('ciudad-684') , Palabra.palabras_dict.get('Granada-706'), position_doc=677 , lugar_sintactico='nmod', importancia = 3390, id=-111))
    list_relaciones.append(Relacion('las', Palabra.palabras_dict.get('ciudad-684') , Palabra.palabras_dict.get('andaluza-693'), position_doc=680 , lugar_sintactico='amod', importancia = 3377, id=-112))
    list_relaciones.append(Relacion('las', Palabra.palabras_dict.get('ciudad-684') , Palabra.palabras_dict.get('Granada-706'), position_doc=680 , lugar_sintactico='nmod', importancia = 3390, id=-113))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('ciudad-684') , Palabra.palabras_dict.get('Granada-706'), position_doc=703 , lugar_sintactico='nmod', importancia = 3390, id=-114))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('ciudad-684') , Palabra.palabras_dict.get('Córdoba-716'), position_doc=703 , lugar_sintactico='conj', importancia = 3400, id=-115))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('Granada-706') , Palabra.palabras_dict.get('Córdoba-716'), position_doc=714 , lugar_sintactico='conj', importancia = 3422, id=-116))
    list_relaciones.append(Relacion('su', Palabra.palabras_dict.get('arquitectura-630') , Palabra.palabras_dict.get('arte-645'), position_doc=627 , lugar_sintactico='conj', importancia = 3275, id=-216))
    return list_palabras, list_relaciones
def test5():
    list_palabras = []
    list_relaciones= []
    list_palabras.append(Palabra('naturaleza', 'NOUN', 'nsubj', 10, 1003, 0, False, 'naturaleza', 3))
    list_palabras.append(Palabra('es', 'AUX', 'cop', 11, 1014, 0, False, 'ser', 14))
    list_palabras.append(Palabra('impresionante', 'ADJ', 'ROOT', 12, 1017, 0, False, 'impresionante', 17))
    list_palabras.append(Palabra('variedad', 'NOUN', 'nmod', 13, 1037, 0, False, 'variedad', 37))
    list_palabras.append(Palabra('paisajes', 'NOUN', 'nmod', 14, 1049, 0, False, 'paisaje', 49))
    list_palabras.append(Palabra('montañas', 'NOUN', 'nmod', 15, 1065, 0, False, 'montaña', 65))
    list_palabras.append(Palabra('majestuosas', 'ADJ', 'amod', 16, 1074, 0, False, 'majestuoso', 74))
    list_palabras.append(Palabra('extensas', 'NOUN', 'conj', 17, 1088, 0, False, 'extensa', 88))
    list_palabras.append(Palabra('llanuras', 'ADJ', 'amod', 18, 1097, 0, False, 'llanura', 97))
    list_palabras.append(Palabra('océanos', 'NOUN', 'nmod', 19, 1112, 0, False, 'océano', 112))
    list_palabras.append(Palabra('ríos', 'NOUN', 'conj', 20, 1122, 0, False, 'río', 122))
    list_palabras.append(Palabra('caudalosos', 'ADJ', 'amod', 21, 1127, 0, False, 'caudaloso', 127))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('naturaleza-3') , Palabra.palabras_dict.get('impresionante-17'), position_doc=0 , lugar_sintactico='ROOT', importancia = 2020, id=-10))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('impresionante-17') , Palabra.palabras_dict.get('variedad-37'), position_doc=31 , lugar_sintactico='nmod', importancia = 2054, id=-11))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('impresionante-17') , Palabra.palabras_dict.get('paisaje-49'), position_doc=31 , lugar_sintactico='nmod', importancia = 2066, id=-12))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('impresionante-17') , Palabra.palabras_dict.get('montaña-65'), position_doc=31 , lugar_sintactico='nmod', importancia = 2082, id=-13))
    list_relaciones.append(Relacion('su', Palabra.palabras_dict.get('impresionante-17') , Palabra.palabras_dict.get('variedad-37'), position_doc=34 , lugar_sintactico='nmod', importancia = 2054, id=-14))
    list_relaciones.append(Relacion('su', Palabra.palabras_dict.get('impresionante-17') , Palabra.palabras_dict.get('paisaje-49'), position_doc=34 , lugar_sintactico='nmod', importancia = 2066, id=-15))
    list_relaciones.append(Relacion('su', Palabra.palabras_dict.get('impresionante-17') , Palabra.palabras_dict.get('montaña-65'), position_doc=34 , lugar_sintactico='nmod', importancia = 2082, id=-16))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('variedad-37') , Palabra.palabras_dict.get('paisaje-49'), position_doc=46 , lugar_sintactico='nmod', importancia = 2086, id=-17))
    list_relaciones.append(Relacion('desde', Palabra.palabras_dict.get('variedad-37') , Palabra.palabras_dict.get('montaña-65'), position_doc=59 , lugar_sintactico='nmod', importancia = 2102, id=-18))
    list_relaciones.append(Relacion('desde', Palabra.palabras_dict.get('variedad-37') , Palabra.palabras_dict.get('majestuoso-74'), position_doc=59 , lugar_sintactico='amod', importancia = 2111, id=-19))
    list_relaciones.append(Relacion('desde', Palabra.palabras_dict.get('variedad-37') , Palabra.palabras_dict.get('llanura-97'), position_doc=59 , lugar_sintactico='amod', importancia = 2134, id=-20))
    list_relaciones.append(Relacion('desde', Palabra.palabras_dict.get('variedad-37') , Palabra.palabras_dict.get('océano-112'), position_doc=59 , lugar_sintactico='nmod', importancia = 2149, id=-21))
    list_relaciones.append(Relacion('desde', Palabra.palabras_dict.get('variedad-37') , Palabra.palabras_dict.get('caudaloso-127'), position_doc=59 , lugar_sintactico='amod', importancia = 2164, id=-22))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('majestuoso-74') , Palabra.palabras_dict.get('extensa-88'), position_doc=86 , lugar_sintactico='conj', importancia = 2162, id=-23))
    list_relaciones.append(Relacion('hasta', Palabra.palabras_dict.get('montaña-65') , Palabra.palabras_dict.get('océano-112'), position_doc=106 , lugar_sintactico='nmod', importancia = 2177, id=-24))
    list_relaciones.append(Relacion('hasta', Palabra.palabras_dict.get('montaña-65') , Palabra.palabras_dict.get('río-122'), position_doc=106 , lugar_sintactico='conj', importancia = 2187, id=-25))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('océano-112') , Palabra.palabras_dict.get('río-122'), position_doc=120 , lugar_sintactico='conj', importancia = 2234, id=-26))
    return list_palabras, list_relaciones
def test6():
    list_palabras = []
    list_relaciones= []
    list_palabras.append(Palabra('educación', 'NOUN', 'nsubj', 10, 1003, 0, False, 'educación', 3))
    list_palabras.append(Palabra('es', 'AUX', 'cop', 11, 1013, 0, False, 'ser', 13))
    list_palabras.append(Palabra('fundamental', 'ADJ', 'ROOT', 12, 1016, 0, False, 'fundamental', 16))
    list_palabras.append(Palabra('desarrollo', 'NOUN', 'nmod', 13, 1036, 0, False, 'desarrollo', 36))
    list_palabras.append(Palabra('personal', 'ADJ', 'amod', 14, 1047, 0, False, 'personal', 47))
    list_palabras.append(Palabra('social', 'ADJ', 'conj', 15, 1058, 0, False, 'social', 58))
    list_palabras.append(Palabra('ya', 'ADV', 'mark', 16, 1066, 0, False, 'ya', 66))
    list_palabras.append(Palabra('conocimientos', 'NOUN', 'obj', 17, 1089, 0, False, 'conocimiento', 89))
    list_palabras.append(Palabra('habilidades', 'NOUN', 'conj', 18, 1105, 0, False, 'habilidad', 105))
    list_palabras.append(Palabra('útiles', 'ADJ', 'amod', 19, 1117, 0, False, 'útil', 117))
    list_palabras.append(Palabra('desafíos', 'NOUN', 'obj', 20, 1139, 0, False, 'desafío', 139))
    list_palabras.append(Palabra('cotidianos', 'ADJ', 'amod', 21, 1148, 0, False, 'cotidiano', 148))
    list_palabras.append(Palabra('así', 'ADV', 'cc', 22, 1160, 0, False, 'así', 160))
    list_palabras.append(Palabra('sociedad', 'NOUN', 'obj', 23, 1216, 0, False, 'sociedad', 216))
    list_palabras.append(Palabra('mundo', 'NOUN', 'conj', 24, 1230, 0, False, 'mundo', 230))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('educación-3') , Palabra.palabras_dict.get('fundamental-16'), position_doc=0 , lugar_sintactico='ROOT', importancia = 2019, id=-10))
    list_relaciones.append(Relacion('para', Palabra.palabras_dict.get('fundamental-16') , Palabra.palabras_dict.get('desarrollo-36'), position_doc=28 , lugar_sintactico='nmod', importancia = 2052, id=-11))
    list_relaciones.append(Relacion('para', Palabra.palabras_dict.get('fundamental-16') , Palabra.palabras_dict.get('personal-47'), position_doc=28 , lugar_sintactico='amod', importancia = 2063, id=-12))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('fundamental-16') , Palabra.palabras_dict.get('desarrollo-36'), position_doc=33 , lugar_sintactico='nmod', importancia = 2052, id=-13))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('fundamental-16') , Palabra.palabras_dict.get('personal-47'), position_doc=33 , lugar_sintactico='amod', importancia = 2063, id=-14))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('personal-47') , Palabra.palabras_dict.get('social-58'), position_doc=56 , lugar_sintactico='conj', importancia = 2105, id=-15))
    list_relaciones.append(Relacion('nos', Palabra.palabras_dict.get('educación-3') , Palabra.palabras_dict.get('fundamental-16'), position_doc=73 , lugar_sintactico='ROOT', importancia = 2019, id=-16))
    list_relaciones.append(Relacion('nos', Palabra.palabras_dict.get('educación-3') , Palabra.palabras_dict.get('ser-13'), position_doc=73 , lugar_sintactico='cop', importancia = 2016, id=-17))
    list_relaciones.append(Relacion('nos', Palabra.palabras_dict.get('educación-3') , Palabra.palabras_dict.get('desarrollo-36'), position_doc=73 , lugar_sintactico='nmod', importancia = 2039, id=-18))
    list_relaciones.append(Relacion('proporciona', Palabra.palabras_dict.get('ya-66') , Palabra.palabras_dict.get('conocimiento-89'), position_doc=77 , lugar_sintactico='obj', importancia = 2155, id=-19))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('conocimiento-89') , Palabra.palabras_dict.get('habilidad-105'), position_doc=103 , lugar_sintactico='conj', importancia = 2194, id=-20))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('conocimiento-89') , Palabra.palabras_dict.get('útil-117'), position_doc=103 , lugar_sintactico='amod', importancia = 2206, id=-21))
    list_relaciones.append(Relacion('enfrentar', Palabra.palabras_dict.get('educación-3') , Palabra.palabras_dict.get('desafío-139'), position_doc=129 , lugar_sintactico='obj', importancia = 2142, id=-22))
    list_relaciones.append(Relacion('enfrentar', Palabra.palabras_dict.get('educación-3') , Palabra.palabras_dict.get('fundamental-16'), position_doc=129 , lugar_sintactico='ROOT', importancia = 2019, id=-23))
    list_relaciones.append(Relacion('enfrentar', Palabra.palabras_dict.get('educación-3') , Palabra.palabras_dict.get('mundo-230'), position_doc=129 , lugar_sintactico='conj', importancia = 2233, id=-24))
    list_relaciones.append(Relacion('enfrentar', Palabra.palabras_dict.get('educación-3') , Palabra.palabras_dict.get('ser-13'), position_doc=129 , lugar_sintactico='cop', importancia = 2016, id=-25))
    list_relaciones.append(Relacion('enfrentar', Palabra.palabras_dict.get('educación-3') , Palabra.palabras_dict.get('desarrollo-36'), position_doc=129 , lugar_sintactico='nmod', importancia = 2039, id=-26))
    list_relaciones.append(Relacion('enfrentar', Palabra.palabras_dict.get('educación-3') , Palabra.palabras_dict.get('sociedad-216'), position_doc=129 , lugar_sintactico='obj', importancia = 2219, id=-27))
    list_relaciones.append(Relacion('enfrentar', Palabra.palabras_dict.get('educación-3') , Palabra.palabras_dict.get('cotidiano-148'), position_doc=129 , lugar_sintactico='amod', importancia = 2151, id=-28))
    list_relaciones.append(Relacion('comprender', Palabra.palabras_dict.get('así-160') , Palabra.palabras_dict.get('mundo-230'), position_doc=174 , lugar_sintactico='conj', importancia = 2390, id=-29))
    list_relaciones.append(Relacion('comprender', Palabra.palabras_dict.get('así-160') , Palabra.palabras_dict.get('sociedad-216'), position_doc=174 , lugar_sintactico='obj', importancia = 2376, id=-30))
    list_relaciones.append(Relacion('participar', Palabra.palabras_dict.get('sociedad-216') , Palabra.palabras_dict.get('mundo-230'), position_doc=187 , lugar_sintactico='conj', importancia = 2446, id=-31))
    list_relaciones.append(Relacion('en', Palabra.palabras_dict.get('sociedad-216') , Palabra.palabras_dict.get('mundo-230'), position_doc=210 , lugar_sintactico='conj', importancia = 2446, id=-32))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('sociedad-216') , Palabra.palabras_dict.get('mundo-230'), position_doc=213 , lugar_sintactico='conj', importancia = 2446, id=-33))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('sociedad-216') , Palabra.palabras_dict.get('mundo-230'), position_doc=225 , lugar_sintactico='conj', importancia = 2446, id=-34))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('sociedad-216') , Palabra.palabras_dict.get('mundo-230'), position_doc=227 , lugar_sintactico='conj', importancia = 2446, id=-35))
    list_relaciones.append(Relacion('que', Palabra.palabras_dict.get('sociedad-216') , Palabra.palabras_dict.get('mundo-230'), position_doc=236 , lugar_sintactico='conj', importancia = 2446, id=-36))
    list_relaciones.append(Relacion('nos', Palabra.palabras_dict.get('sociedad-216') , Palabra.palabras_dict.get('mundo-230'), position_doc=240 , lugar_sintactico='conj', importancia = 2446, id=-37))
    list_relaciones.append(Relacion('rodea', Palabra.palabras_dict.get('sociedad-216') , Palabra.palabras_dict.get('mundo-230'), position_doc=244 , lugar_sintactico='conj', importancia = 2446, id=-38))
    list_relaciones.append(Relacion('para', Palabra.palabras_dict.get('fundamental-16') , Palabra.palabras_dict.get('desarrollo-36'), position_doc=28 , lugar_sintactico='nmod', importancia = 2052, id=-40))
    list_relaciones.append(Relacion('que', Palabra.palabras_dict.get('sociedad-216') , Palabra.palabras_dict.get('mundo-230'), position_doc=236 , lugar_sintactico='conj', importancia = 2446, id=-67))
    return list_palabras, list_relaciones

def test7():
    list_palabras= []
    list_relaciones= []
    list_palabras.append(Palabra('cuerpo', 'NOUN', 'nsubj', 10, 1003, 0, False, 'cuerpo', 3))
    list_palabras.append(Palabra('humano', 'ADJ', 'amod', 11, 1010, 0, False, 'humano', 10))
    list_palabras.append(Palabra('es', 'AUX', 'cop', 12, 1017, 0, False, 'ser', 17))
    list_palabras.append(Palabra('maravilla', 'NOUN', 'ROOT', 13, 1024, 0, False, 'maravilla', 24))
    list_palabras.append(Palabra('biología', 'NOUN', 'nmod', 14, 1040, 0, False, 'biología', 40))
    list_palabras.append(Palabra('sistemas', 'NOUN', 'obl', 15, 1058, 0, False, 'sistema', 58))
    list_palabras.append(Palabra('complejos', 'ADJ', 'amod', 16, 1067, 0, False, 'complejo', 67))
    list_palabras.append(Palabra('interconectados', 'ADJ', 'amod', 17, 1077, 0, False, 'interconectado', 77))
    list_palabras.append(Palabra('sistema', 'NOUN', 'nmod', 18, 1102, 0, False, 'sistema', 102))
    list_palabras.append(Palabra('nervioso', 'ADJ', 'amod', 19, 1110, 0, False, 'nervioso', 110))
    list_palabras.append(Palabra('funciones', 'NOUN', 'obj', 20, 1136, 0, False, 'función', 136))
    list_palabras.append(Palabra('cuerpo', 'NOUN', 'nmod', 21, 1150, 0, False, 'cuerpo', 150))
    list_palabras.append(Palabra('sistema', 'NOUN', 'conj', 22, 1162, 0, False, 'sistema', 162))
    list_palabras.append(Palabra('cardiovascular', 'ADJ', 'amod', 23, 1170, 0, False, 'cardiovascular', 170))
    list_palabras.append(Palabra('flujo', 'NOUN', 'nsubj', 24, 1201, 0, False, 'flujo', 201))
    list_palabras.append(Palabra('sanguíneo', 'ADJ', 'amod', 25, 1207, 0, False, 'sanguíneo', 207))
    list_palabras.append(Palabra('así', 'ADV', 'cc', 26, 1218, 0, False, 'así', 218))
    list_palabras.append(Palabra('órganos', 'NOUN', 'conj', 27, 1227, 0, False, 'órgano', 227))
    list_palabras.append(Palabra('vitales', 'ADJ', 'amod', 28, 1235, 0, False, 'vital', 235))
    list_palabras.append(Palabra('corazón', 'NOUN', 'nmod', 29, 1251, 0, False, 'corazón', 251))
    list_palabras.append(Palabra('pulmones', 'NOUN', 'conj', 30, 1265, 0, False, 'pulmón', 265))
    list_palabras.append(Palabra('vivos', 'ADJ', 'amod', 31, 1311, 0, False, 'vivo', 311))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('cuerpo-3') , Palabra.palabras_dict.get('maravilla-24'), position_doc=0 , lugar_sintactico='ROOT', importancia = 2027, id=-10))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('cuerpo-3') , Palabra.palabras_dict.get('humano-10'), position_doc=0 , lugar_sintactico='amod', importancia = 2013, id=-11))
    list_relaciones.append(Relacion('una', Palabra.palabras_dict.get('cuerpo-3') , Palabra.palabras_dict.get('maravilla-24'), position_doc=20 , lugar_sintactico='ROOT', importancia = 2027, id=-12))
    list_relaciones.append(Relacion('una', Palabra.palabras_dict.get('cuerpo-3') , Palabra.palabras_dict.get('ser-17'), position_doc=20 , lugar_sintactico='cop', importancia = 2020, id=-13))
    list_relaciones.append(Relacion('una', Palabra.palabras_dict.get('cuerpo-3') , Palabra.palabras_dict.get('biología-40'), position_doc=20 , lugar_sintactico='nmod', importancia = 2043, id=-14))
    list_relaciones.append(Relacion('una', Palabra.palabras_dict.get('cuerpo-3') , Palabra.palabras_dict.get('sistema-58'), position_doc=20 , lugar_sintactico='obl', importancia = 2061, id=-15))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('maravilla-24') , Palabra.palabras_dict.get('biología-40'), position_doc=34 , lugar_sintactico='nmod', importancia = 2064, id=-16))
    list_relaciones.append(Relacion('la', Palabra.palabras_dict.get('maravilla-24') , Palabra.palabras_dict.get('biología-40'), position_doc=37 , lugar_sintactico='nmod', importancia = 2064, id=-17))
    list_relaciones.append(Relacion('con', Palabra.palabras_dict.get('maravilla-24') , Palabra.palabras_dict.get('sistema-58'), position_doc=50 , lugar_sintactico='obl', importancia = 2082, id=-18))
    list_relaciones.append(Relacion('con', Palabra.palabras_dict.get('maravilla-24') , Palabra.palabras_dict.get('complejo-67'), position_doc=50 , lugar_sintactico='amod', importancia = 2091, id=-19))
    list_relaciones.append(Relacion('con', Palabra.palabras_dict.get('maravilla-24') , Palabra.palabras_dict.get('interconectado-77'), position_doc=50 , lugar_sintactico='amod', importancia = 2101, id=-20))
    list_relaciones.append(Relacion('con', Palabra.palabras_dict.get('maravilla-24') , Palabra.palabras_dict.get('sistema-102'), position_doc=50 , lugar_sintactico='nmod', importancia = 2126, id=-21))
    list_relaciones.append(Relacion('sus', Palabra.palabras_dict.get('maravilla-24') , Palabra.palabras_dict.get('sistema-58'), position_doc=54 , lugar_sintactico='obl', importancia = 2082, id=-22))
    list_relaciones.append(Relacion('sus', Palabra.palabras_dict.get('maravilla-24') , Palabra.palabras_dict.get('complejo-67'), position_doc=54 , lugar_sintactico='amod', importancia = 2091, id=-23))
    list_relaciones.append(Relacion('sus', Palabra.palabras_dict.get('maravilla-24') , Palabra.palabras_dict.get('interconectado-77'), position_doc=54 , lugar_sintactico='amod', importancia = 2101, id=-24))
    list_relaciones.append(Relacion('sus', Palabra.palabras_dict.get('maravilla-24') , Palabra.palabras_dict.get('sistema-102'), position_doc=54 , lugar_sintactico='nmod', importancia = 2126, id=-25))
    list_relaciones.append(Relacion('como', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('sistema-102'), position_doc=94 , lugar_sintactico='nmod', importancia = 2160, id=-26))
    list_relaciones.append(Relacion('como', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('nervioso-110'), position_doc=94 , lugar_sintactico='amod', importancia = 2168, id=-27))
    list_relaciones.append(Relacion('como', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('órgano-227'), position_doc=94 , lugar_sintactico='conj', importancia = 2285, id=-28))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('sistema-102'), position_doc=99 , lugar_sintactico='nmod', importancia = 2160, id=-29))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('nervioso-110'), position_doc=99 , lugar_sintactico='amod', importancia = 2168, id=-30))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('órgano-227'), position_doc=99 , lugar_sintactico='conj', importancia = 2285, id=-31))
    list_relaciones.append(Relacion('que', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('sistema-102'), position_doc=119 , lugar_sintactico='nmod', importancia = 2160, id=-32))
    list_relaciones.append(Relacion('que', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('nervioso-110'), position_doc=119 , lugar_sintactico='amod', importancia = 2168, id=-33))
    list_relaciones.append(Relacion('que', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('órgano-227'), position_doc=119 , lugar_sintactico='conj', importancia = 2285, id=-34))
    list_relaciones.append(Relacion('coordina', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('función-136'), position_doc=123 , lugar_sintactico='obj', importancia = 2194, id=-35))
    list_relaciones.append(Relacion('coordina', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('sistema-102'), position_doc=123 , lugar_sintactico='nmod', importancia = 2160, id=-36))
    list_relaciones.append(Relacion('coordina', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('nervioso-110'), position_doc=123 , lugar_sintactico='amod', importancia = 2168, id=-37))
    list_relaciones.append(Relacion('coordina', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('órgano-227'), position_doc=123 , lugar_sintactico='conj', importancia = 2285, id=-38))
    list_relaciones.append(Relacion('coordina', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('cuerpo-150'), position_doc=123 , lugar_sintactico='nmod', importancia = 2208, id=-39))
    list_relaciones.append(Relacion('coordina', Palabra.palabras_dict.get('sistema-58') , Palabra.palabras_dict.get('sistema-162'), position_doc=123 , lugar_sintactico='conj', importancia = 2220, id=-40))
    list_relaciones.append(Relacion('las', Palabra.palabras_dict.get('función-136') , Palabra.palabras_dict.get('cuerpo-150'), position_doc=132 , lugar_sintactico='nmod', importancia = 2286, id=-41))
    list_relaciones.append(Relacion('las', Palabra.palabras_dict.get('función-136') , Palabra.palabras_dict.get('sistema-162'), position_doc=132 , lugar_sintactico='conj', importancia = 2298, id=-42))
    list_relaciones.append(Relacion('del', Palabra.palabras_dict.get('función-136') , Palabra.palabras_dict.get('cuerpo-150'), position_doc=146 , lugar_sintactico='nmod', importancia = 2286, id=-43))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('función-136') , Palabra.palabras_dict.get('sistema-162'), position_doc=157 , lugar_sintactico='conj', importancia = 2298, id=-44))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('función-136') , Palabra.palabras_dict.get('cardiovascular-170'), position_doc=157 , lugar_sintactico='amod', importancia = 2306, id=-45))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('función-136') , Palabra.palabras_dict.get('sistema-162'), position_doc=159 , lugar_sintactico='conj', importancia = 2298, id=-46))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('función-136') , Palabra.palabras_dict.get('cardiovascular-170'), position_doc=159 , lugar_sintactico='amod', importancia = 2306, id=-47))
    list_relaciones.append(Relacion('que', Palabra.palabras_dict.get('función-136') , Palabra.palabras_dict.get('sistema-162'), position_doc=185 , lugar_sintactico='conj', importancia = 2298, id=-48))
    list_relaciones.append(Relacion('que', Palabra.palabras_dict.get('función-136') , Palabra.palabras_dict.get('cardiovascular-170'), position_doc=185 , lugar_sintactico='amod', importancia = 2306, id=-49))
    list_relaciones.append(Relacion('mantiene', Palabra.palabras_dict.get('función-136') , Palabra.palabras_dict.get('flujo-201'), position_doc=189 , lugar_sintactico='nsubj', importancia = 2337, id=-50))
    list_relaciones.append(Relacion('mantiene', Palabra.palabras_dict.get('función-136') , Palabra.palabras_dict.get('sistema-162'), position_doc=189 , lugar_sintactico='conj', importancia = 2298, id=-51))
    list_relaciones.append(Relacion('mantiene', Palabra.palabras_dict.get('función-136') , Palabra.palabras_dict.get('cardiovascular-170'), position_doc=189 , lugar_sintactico='amod', importancia = 2306, id=-52))
    list_relaciones.append(Relacion('mantiene', Palabra.palabras_dict.get('función-136') , Palabra.palabras_dict.get('sanguíneo-207'), position_doc=189 , lugar_sintactico='amod', importancia = 2343, id=-53))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('flujo-201') , Palabra.palabras_dict.get('sanguíneo-207'), position_doc=198 , lugar_sintactico='amod', importancia = 2408, id=-54))
    list_relaciones.append(Relacion('como', Palabra.palabras_dict.get('así-218') , Palabra.palabras_dict.get('órgano-227'), position_doc=222 , lugar_sintactico='conj', importancia = 2445, id=-55))
    list_relaciones.append(Relacion('como', Palabra.palabras_dict.get('órgano-227') , Palabra.palabras_dict.get('corazón-251'), position_doc=243 , lugar_sintactico='nmod', importancia = 2478, id=-56))
    list_relaciones.append(Relacion('el', Palabra.palabras_dict.get('órgano-227') , Palabra.palabras_dict.get('corazón-251'), position_doc=248 , lugar_sintactico='nmod', importancia = 2478, id=-57))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('órgano-227') , Palabra.palabras_dict.get('pulmón-265'), position_doc=259 , lugar_sintactico='conj', importancia = 2492, id=-58))
    list_relaciones.append(Relacion('los', Palabra.palabras_dict.get('órgano-227') , Palabra.palabras_dict.get('pulmón-265'), position_doc=261 , lugar_sintactico='conj', importancia = 2492, id=-59))
    list_relaciones.append(Relacion('que', Palabra.palabras_dict.get('órgano-227') , Palabra.palabras_dict.get('pulmón-265'), position_doc=274 , lugar_sintactico='conj', importancia = 2492, id=-60))
    list_relaciones.append(Relacion('trabajan', Palabra.palabras_dict.get('órgano-227') , Palabra.palabras_dict.get('pulmón-265'), position_doc=278 , lugar_sintactico='conj', importancia = 2492, id=-61))
    list_relaciones.append(Relacion('juntos', Palabra.palabras_dict.get('órgano-227') , Palabra.palabras_dict.get('pulmón-265'), position_doc=287 , lugar_sintactico='conj', importancia = 2492, id=-62))
    list_relaciones.append(Relacion('para', Palabra.palabras_dict.get('sistema-102') , Palabra.palabras_dict.get('órgano-227'), position_doc=294 , lugar_sintactico='conj', importancia = 2329, id=-63))
    list_relaciones.append(Relacion('para', Palabra.palabras_dict.get('sistema-102') , Palabra.palabras_dict.get('así-218'), position_doc=294 , lugar_sintactico='cc', importancia = 2320, id=-64))
    list_relaciones.append(Relacion('para', Palabra.palabras_dict.get('sistema-102') , Palabra.palabras_dict.get('vital-235'), position_doc=294 , lugar_sintactico='amod', importancia = 2337, id=-65))
    list_relaciones.append(Relacion('para', Palabra.palabras_dict.get('sistema-102') , Palabra.palabras_dict.get('corazón-251'), position_doc=294 , lugar_sintactico='nmod', importancia = 2353, id=-66))
    list_relaciones.append(Relacion('para', Palabra.palabras_dict.get('sistema-102') , Palabra.palabras_dict.get('pulmón-265'), position_doc=294 , lugar_sintactico='conj', importancia = 2367, id=-67))
    list_relaciones.append(Relacion('mantenernos', Palabra.palabras_dict.get('sistema-102') , Palabra.palabras_dict.get('vivo-311'), position_doc=299 , lugar_sintactico='amod', importancia = 2413, id=-68))
    list_relaciones.append(Relacion('mantenernos', Palabra.palabras_dict.get('sistema-102') , Palabra.palabras_dict.get('órgano-227'), position_doc=299 , lugar_sintactico='conj', importancia = 2329, id=-69))
    list_relaciones.append(Relacion('mantenernos', Palabra.palabras_dict.get('sistema-102') , Palabra.palabras_dict.get('así-218'), position_doc=299 , lugar_sintactico='cc', importancia = 2320, id=-70))
    list_relaciones.append(Relacion('mantenernos', Palabra.palabras_dict.get('sistema-102') , Palabra.palabras_dict.get('vital-235'), position_doc=299 , lugar_sintactico='amod', importancia = 2337, id=-71))
    list_relaciones.append(Relacion('mantenernos', Palabra.palabras_dict.get('sistema-102') , Palabra.palabras_dict.get('corazón-251'), position_doc=299 , lugar_sintactico='nmod', importancia = 2353, id=-72))
    list_relaciones.append(Relacion('mantenernos', Palabra.palabras_dict.get('sistema-102') , Palabra.palabras_dict.get('pulmón-265'), position_doc=299 , lugar_sintactico='conj', importancia = 2367, id=-73))
    return list_palabras, list_relaciones


def test8():
    list_palabras= []
    list_relaciones= []
    list_palabras.append(Palabra('perro', 'PROPN', 'nsubj', 10, 1003, 0, False, 'perro', 3))
    list_palabras.append(Palabra('es', 'AUX', 'cop', 11, 1009, 0, False, 'ser', 9))
    list_palabras.append(Palabra('tres', 'NUM', 'nummod', 12, 1035, 0, False, 'tres', 35))
    list_palabras.append(Palabra('años', 'NOUN', 'obl', 13, 1040, 0, False, 'año', 40))
    list_palabras.append(Palabra('pelota', 'NOUN', 'obl', 14, 1068, 0, False, 'pelota', 68))
    list_palabras.append(Palabra('parque', 'NOUN', 'obl', 15, 1081, 0, False, 'parque', 81))
    list_palabras.append(Palabra('bienvenida', 'NOUN', 'obj', 16, 1107, 0, False, 'bienvenida', 107))
    list_palabras.append(Palabra('cola', 'NOUN', 'obj', 17, 1130, 0, False, 'cola', 130))
    list_palabras.append(Palabra('llego', 'NOUN', 'advcl', 18, 1142, 0, False, 'llego', 142))
    list_palabras.append(Palabra('casa', 'NOUN', 'obl', 19, 1150, 0, False, 'casa', 150))
    list_relaciones.append(Relacion('golden', Palabra.palabras_dict.get('perro-3') , Palabra.palabras_dict.get('ser-9'), position_doc=15 , lugar_sintactico='cop', importancia = 2012, id=-10))
    list_relaciones.append(Relacion('retriever', Palabra.palabras_dict.get('tres-35') , Palabra.palabras_dict.get('año-40'), position_doc=22 , lugar_sintactico='obl', importancia = 2075, id=-11))
    list_relaciones.append(Relacion('de', Palabra.palabras_dict.get('tres-35') , Palabra.palabras_dict.get('año-40'), position_doc=32 , lugar_sintactico='obl', importancia = 2075, id=-12))
    list_relaciones.append(Relacion('que', Palabra.palabras_dict.get('tres-35') , Palabra.palabras_dict.get('año-40'), position_doc=45 , lugar_sintactico='obl', importancia = 2075, id=-13))
    list_relaciones.append(Relacion('adora', Palabra.palabras_dict.get('tres-35') , Palabra.palabras_dict.get('año-40'), position_doc=49 , lugar_sintactico='obl', importancia = 2075, id=-14))
    list_relaciones.append(Relacion('jugar', Palabra.palabras_dict.get('pelota-68') , Palabra.palabras_dict.get('parque-81'), position_doc=55 , lugar_sintactico='obl', importancia = 2149, id=-15))
    list_relaciones.append(Relacion('moviendo', Palabra.palabras_dict.get('cola-130') , Palabra.palabras_dict.get('llego-142'), position_doc=118 , lugar_sintactico='advcl', importancia = 2272, id=-16))
    list_relaciones.append(Relacion('cuando', Palabra.palabras_dict.get('llego-142') , Palabra.palabras_dict.get('casa-150'), position_doc=135 , lugar_sintactico='obl', importancia = 2292, id=-17))
    list_relaciones.append(Relacion('a', Palabra.palabras_dict.get('llego-142') , Palabra.palabras_dict.get('casa-150'), position_doc=148 , lugar_sintactico='obl', importancia = 2292, id=-18))
    list_relaciones.append(Relacion('un', Palabra.palabras_dict.get('ser-9') , Palabra.palabras_dict.get('golden-15'), position_doc=12 , lugar_sintactico='ROOT', importancia = 2024, id=-23))
    list_relaciones.append(Relacion('y', Palabra.palabras_dict.get('ser-9') , Palabra.palabras_dict.get('golden-15'), position_doc=88 , lugar_sintactico='ROOT', importancia = 2024, id=-35))
    list_relaciones.append(Relacion('siempre', Palabra.palabras_dict.get('ser-9') , Palabra.palabras_dict.get('golden-15'), position_doc=90 , lugar_sintactico='ROOT', importancia = 2024, id=-38))
    list_relaciones.append(Relacion('me', Palabra.palabras_dict.get('ser-9') , Palabra.palabras_dict.get('golden-15'), position_doc=98 , lugar_sintactico='ROOT', importancia = 2024, id=-41))
    list_relaciones.append(Relacion('da', Palabra.palabras_dict.get('ser-9') , Palabra.palabras_dict.get('bienvenida-107'), position_doc=101 , lugar_sintactico='obj', importancia = 2116, id=-44))
    return list_palabras, list_relaciones

#test1() # 6
#test2() # 14
#test3() # 16
#test4() # 53++
#test5() # 12
#test6() # 15
#test7() # 22
#test8() # 10


#list_palabras, list_relaciones = test5()
#list_palabras, list_relaciones = test2()
list_palabras, list_relaciones = test5()
generate_graph(texto, list_palabras, list_relaciones)


ACTIVA_WEB = False

if ACTIVA_WEB:
    ############# Web:
    from flask import Flask, send_file
    app = Flask(__name__)
    import requests
    from PIL import Image
    import io
    #######################

    @app.route("/")
    def display_graph():
        fig = generate_graph(texto, list_palabras, list_relaciones)
        fig.savefig('graph.png', bbox_inches='tight')
        return send_file('graph.png', mimetype='image/png')

    if __name__ == "__main__":
        app.run(debug=True)






#test2() # 14
#generate_graph(texto, list_palabras, list_relaciones)
#test4() # 53
#test6() # 15
#test5() # 12

#generate_graph(texto, list_palabras, list_relaciones)
#from grafico12 import print_graph
#print_graph(texto, list_palabras, list_relaciones)


